title: From Image to Map
description: Georeferencing the Van Berckenrode map of Amsterdam
credits: CREDITS.md

slideshows:
  - id: main
    path: slideshows/main
    start:
      location:
        zoom: 18
      warpedMaps:
          - url: https://annotations.allmaps.org/maps/e9aa6ec10276bf65@d2d0044d129ea2d5
            caption: Van Berckenrode map of Amsterdam
            provenance: Allard Pierson
            homepage: https://hdl.handle.net/11245/3.39844
            useBearing: true
            options:
              applyMask: false
              transformationType: helmert

# This key is for the template demo. When copying or forking this repository,
# get your own key at https://protomaps.com/api and replace it below.
protomaps:
  key: ca7652ec836f269a
